// <auto-generated />
using EastsydApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EastsydApp.API.Data.EDMigrations
{
    [DbContext(typeof(EastsydDbContext))]
    [Migration("20240411070425_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.17");

            modelBuilder.Entity("EastsydApp.API.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("EastsydApp.API.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("EastsydApp.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A kit provided by Glossier, containing skin care, hair care and makeup products",
                            ImageURL = "/Images/Skin-Care/Beauty Kit.jpg",
                            Name = "Glossier - Beauty Kit",
                            Price = 100m,
                            ProductCategoryId = 1,
                            Qty = 100
                        },
                        new
                        {
                            Id = 2,
                            Description = "A kit provided by Curology, containing skin care products",
                            ImageURL = "/Images/Skin-Care/elfBeauty.jpg",
                            Name = "elf - Make Up Kit",
                            Price = 50m,
                            ProductCategoryId = 1,
                            Qty = 45
                        },
                        new
                        {
                            Id = 3,
                            Description = "Brown Powder by MAC",
                            ImageURL = "/Images/Skin-Care/Mc Beauty.jpg",
                            Name = "Mac  Foundation Powder",
                            Price = 30m,
                            ProductCategoryId = 1,
                            Qty = 85
                        },
                        new
                        {
                            Id = 4,
                            Description = "A kit provided by Curology, it makes ypur lip pop and stand out",
                            ImageURL = "/Images/Skin-Care/Lip Gloss two.jpg",
                            Name = "Rare Beauty Lip Gloss",
                            Price = 20m,
                            ProductCategoryId = 1,
                            Qty = 30
                        },
                        new
                        {
                            Id = 5,
                            Description = "A kit provided by Schwarzkopf, it makes ypur lip pop and stand out",
                            ImageURL = "/Images/Skin-Care/Lip Stick.jpg",
                            Name = "Lip Glow",
                            Price = 50m,
                            ProductCategoryId = 1,
                            Qty = 60
                        },
                        new
                        {
                            Id = 6,
                            Description = "Air Pods - in-ear wireless headphones",
                            ImageURL = "/Images/Electronics/Airpod 3.jpg",
                            Name = "Apple Air Pod",
                            Price = 100m,
                            ProductCategoryId = 3,
                            Qty = 120
                        },
                        new
                        {
                            Id = 7,
                            Description = "Airpods  3 ",
                            ImageURL = "/Images/Electronics/Airpod and pack.jpg",
                            Name = "Airpod & Pack",
                            Price = 40m,
                            ProductCategoryId = 3,
                            Qty = 200
                        },
                        new
                        {
                            Id = 8,
                            Description = "On-ear Black Headphones - Beats by Dr Dre",
                            ImageURL = "/Images/Electronics/Beats Headphone.jpg",
                            Name = "Beats Headphones",
                            Price = 40m,
                            ProductCategoryId = 3,
                            Qty = 300
                        },
                        new
                        {
                            Id = 9,
                            Description = "Black Tozo Headbuds",
                            ImageURL = "/Images/Electronics/Tozo Earbud.jpg",
                            Name = "Tozo buds",
                            Price = 600m,
                            ProductCategoryId = 3,
                            Qty = 20
                        },
                        new
                        {
                            Id = 10,
                            Description = "Tripod",
                            ImageURL = "/Images/Electronics/Tripod.jpg",
                            Name = "Tripod",
                            Price = 500m,
                            ProductCategoryId = 3,
                            Qty = 15
                        },
                        new
                        {
                            Id = 11,
                            Description = "Black Iphone 11 Pro",
                            ImageURL = "/Images/Electronics/Iphone.jpg",
                            Name = "Iphone 11",
                            Price = 100m,
                            ProductCategoryId = 3,
                            Qty = 60
                        },
                        new
                        {
                            Id = 12,
                            Description = "Very comfortable black chair",
                            ImageURL = "/Images/Furniture/bigChair.jpg",
                            Name = "Black Big Chair",
                            Price = 50m,
                            ProductCategoryId = 2,
                            Qty = 212
                        },
                        new
                        {
                            Id = 13,
                            Description = "Very comfortable pink and black leather gaming chair",
                            ImageURL = "/Images/Furniture/chair 2.jpg",
                            Name = "Black and Pink Gaming Chair",
                            Price = 50m,
                            ProductCategoryId = 2,
                            Qty = 112
                        },
                        new
                        {
                            Id = 14,
                            Description = "Very comfortable lounge chair",
                            ImageURL = "/Images/Furniture/chair one.jpg",
                            Name = "Lounge Chair",
                            Price = 70m,
                            ProductCategoryId = 2,
                            Qty = 90
                        },
                        new
                        {
                            Id = 15,
                            Description = "Office Table Lamp",
                            ImageURL = "/Images/Furniture/Lamp.jpg",
                            Name = "Solid Lamp",
                            Price = 20m,
                            ProductCategoryId = 2,
                            Qty = 73
                        },
                        new
                        {
                            Id = 16,
                            Description = "Very comfortable office desk",
                            ImageURL = "/Images/Furniture/Desk.jpg",
                            Name = "Desk",
                            Price = 70m,
                            ProductCategoryId = 2,
                            Qty = 90
                        },
                        new
                        {
                            Id = 17,
                            Description = "Ash family chairs, full set.",
                            ImageURL = "/Images/Furniture/family chair.jpg",
                            Name = "Full set Sofa",
                            Price = 15m,
                            ProductCategoryId = 2,
                            Qty = 100
                        },
                        new
                        {
                            Id = 18,
                            Description = "Comfortable addidas Sneakers in most sizes",
                            ImageURL = "/Images/Shoes/Addidas.jpg",
                            Name = "Addidas Sneakers",
                            Price = 100m,
                            ProductCategoryId = 4,
                            Qty = 50
                        },
                        new
                        {
                            Id = 19,
                            Description = "Brown Chelsea Boots  - available in most sizes",
                            ImageURL = "/Images/Shoes/Chelsea Boot.jpg",
                            Name = "Chelsea Boot",
                            Price = 150m,
                            ProductCategoryId = 4,
                            Qty = 60
                        },
                        new
                        {
                            Id = 20,
                            Description = " Nike Air Max - available in most sizes",
                            ImageURL = "/Images/Shoes/Nike Air Max.jpg",
                            Name = " Nike Air Max",
                            Price = 200m,
                            ProductCategoryId = 4,
                            Qty = 70
                        },
                        new
                        {
                            Id = 21,
                            Description = "Nike Dunk Low - available in most sizes",
                            ImageURL = "/Images/Shoes/Nike Dunk Low.jpg",
                            Name = "Nike Dunk Low",
                            Price = 120m,
                            ProductCategoryId = 4,
                            Qty = 120
                        },
                        new
                        {
                            Id = 22,
                            Description = "Addidas  Busekitz - available in most sizes",
                            ImageURL = "/Images/Shoes/Puma.jpg",
                            Name = "Addidas  Busekitz",
                            Price = 200m,
                            ProductCategoryId = 4,
                            Qty = 100
                        },
                        new
                        {
                            Id = 23,
                            Description = "Sketchers Trainers - available in most sizes",
                            ImageURL = "/Images/Shoes/Sketchers.jpg",
                            Name = "Sketchers Trainers",
                            Price = 50m,
                            ProductCategoryId = 4,
                            Qty = 150
                        });
                });

            modelBuilder.Entity("EastsydApp.API.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconCss")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconCss = "fa-solid fa-pump-soap",
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 2,
                            IconCss = "fa-solid fa-couch",
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 3,
                            IconCss = "fa-solid fa-plug",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 4,
                            IconCss = "fa-solid fa-shoe-prints",
                            Name = "Shoes"
                        });
                });

            modelBuilder.Entity("EastsydApp.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserName = "Bob"
                        },
                        new
                        {
                            Id = 2,
                            UserName = "Sarah"
                        });
                });

            modelBuilder.Entity("EastsydApp.API.Models.Product", b =>
                {
                    b.HasOne("EastsydApp.API.Models.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("EastsydApp.API.Models.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
